services:
  - type: web
    name: jonahfidel-to-do-list
    runtime: node
    plan: 0.5c-512mb
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: NODE_ENV
        value: production
    disk:
      name: todo-data
      mountPath: /opt/render/project/src/db
      sizeGB: 1
