services:
  - type: web
    name: jonahfidel-to-do-list
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: NODE_ENV
        value: production
